### PR TITLE
Fix and cleanup IEC.postman_collection.json

### PR DESCRIPTION
**Pull request by maorcc**
## What changes do you are proposing?
I have done the following fixes and cleanups.  The first one fixes a bug, the rest are mostly cleanups.  Each fix is its own commit.

1.  Remove the duplicate Content-Type header in step 5
Fix Auth step 5 remove Content-Type: application/json. Postman adds auto generates the correct Content-Type of application/x-www-form-urlencoded instead. Having the content type twice in Postman causes it to behave inconsistently, and sometimes works but not always. This change should fix it.

2. Remove type "text" from content-type parameters.  
This was done automatically by the export of the latest version of Postman.

3. Remove Content-type of application/json from step 4
Done because this step is a GET request that should not have a Content-Type header. It was disabled anyway, but I removed it as it was wrong.

4. Sort APIs list
Moved the Devices api upwards to its correct location in the list of APIs, because it must run before the RemoteReadingRange API.

5. Clean double slash in URL
Postman removes the double slash ("//") from all URLs on import. 
This empty path element makes no difference, and the API works with and without it.
This extra slash is probably a bug in the IEC front-end, and was not intended to be there by their IEC API backend developers.

## How did you test these changes? 
To test I cleared my Postman workspace. Re-imported the file, and tested that all APIs are working and returning valid data.

**Closing issues**

___

### **PR Type**
enhancement, bug fix

___

### **Description**
- Removed duplicate `Content-Type` headers in multiple steps to ensure consistent behavior in Postman.
- Removed `type: "text"` from `Content-Type` and `Accept` headers as per the latest Postman export.
- Corrected `Content-Type` for GET requests, ensuring they do not have a `Content-Type` header.
- Sorted APIs list, moving the `Devices` API upwards to its correct location.
- Cleaned double slashes in URLs, which were removed by Postman on import.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>IEC.postman_collection.json</strong><dd><code>Fix headers, clean URLs, and reorder APIs in Postman collection.</code></dd></summary>
<hr>
      
IEC.postman_collection.json

<li>Removed duplicate <code>Content-Type</code> headers in multiple steps.<br> <li> Removed <code>type: "text"</code> from <code>Content-Type</code> and <code>Accept</code> headers.<br> <li> Corrected <code>Content-Type</code> for GET requests.<br> <li> Sorted APIs list and moved <code>Devices</code> API upwards.<br> <li> Cleaned double slashes in URLs.<br>

</details>
    

  </td>
  <td><a href="https://github.com/GuyKh/py-iec-api/pull/113/files#diff-7e7d847a723b947dd48f4ba9761b47605d18bf7b85dc2af430fbfdd937614806">+117/-146</a></td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by GuyKh** [comment]
@maorcc I have to praise you for the clear and VERY informative PR.
I wish all devs were working this way.
Kudos! 🎉

**Comment by GuyKh** [comment]
@maorcc The only part I'm concerned about is the double-slash. From tests I've done when I wrote this, IEC API failed on single slash and worked on double, for some reason.

I want to make sure you've tested this

**Comment by maorcc** [comment]
Yes, after doing all the changes, including the removal of double slashes I tested it as I described above:
> To test I cleared my Postman workspace. Re-imported the file, and tested that all APIs are working and returning valid data.

**Comment by GuyKh** [comment]
Thanks again for your work

**Pull request merged**
