### PR TITLE
fix: API Change: CustomerAccount.name+last_name don't return on API

### PR DESCRIPTION
**Pull request by GuyKh**
## What changes do you are proposing?
API Change: CustomerAccount.name+last_name don't return on API

## How did you test these changes? 

**Closing issues**
#155

### CODE REVIEW

**Comment by tzagim** [comment]
Thank you very much!
Only one trailing error appears:
```
Message: 'Failed fetching kWh Tariff'
Arguments: (IECError('(Code 204): No Content'),)
```

**Comment by GuyKh** [comment]
Again - why on this thread? :/

**Comment by GuyKh** [comment]
@tzagim - make sure you use the **latest** version of `iec-custom-components`, I've changed the path for fetching the KWH price recently

**Comment by tzagim** [comment]
@GuyKh 
Fixed after a few more system reboots.
TNX

**Pull request merged**
